---
version: 0.0.2a
slug: coredns
name: coredns
description: CoreDNS is a flexible DNS server written in Go.
url: https://github.com/SharkyRawr/hass-coredns
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: sophiefox/hass-coredns-{arch}
codenotary: cas@sophie.lgbt
init: false
map:
  - share
options:
  defaults:
    - 8.8.8.8
    - 8.4.4.4
    - 1.1.1.1
    - 1.0.0.1
  customize:
    active: false
    folder: coredns
  acl_allow:
    - 192.168.0.0/16
    - 10.0.0.0/8
ports:
  53/tcp: 53
  53/udp: 53
schema:
  defaults:
    - str
  acl_allow:
    - str
  customize:
    active: bool
    folder: str
startup: system
